### PR TITLE
Rename everything

### PR DESCRIPTION
**Pull request by DLu**
* Changes `benchmark_msgs` to `metro_benchmark_msgs`
 * Changes `benchmark_utils` to `metro_benchmark_pub`
 * Changes `collision_msgs` to `collision_log_msgs`
 * Changes `Collision.msg` to `NamedCollision.msg`

### CODE REVIEW

**Comment by SteveMacenski** [comment]
I know no one asked me, but may I suggest just adding `metro_` prefix to these? `compute_benchmark_msgs` really isn't much less general than `benchmark_msgs`

- `metro_benchmarking_msgs`
- `metro_benchmarking_utils` `metro_benchmarking`

**Comment by DLu** [comment]
@SteveMacenski For full context, see the conversation at https://github.com/ros/rosdistro/pull/38369#pullrequestreview-1601949499

**Review by emersonknapp — APPROVED** [review]
I'll just leave this as my registered dissent that I think these are unnecessarily broad and that a `metro_` prefix would make me happier too, but also nobody else is contending for the specific package names and i'm not the boss of you. Let's move them forward

**Comment by SteveMacenski** [comment]
I saw that thread in rosdistro, which is what led me here :smile: 

It feels too general to me unless (1) its going to live in ros standard messages stack or (2) has more complete set of msgs or (3) has already broad historical support.

Seems like if that name is important, it should be targeting (1)

But also not the boss of you :shrug: 

I feel like CCing @vmayoral if we're talking about (1) or (2)

**Pull request merged**
